#!/bin/bash

# 
#  do_run.sh
#  TwoCC
#  
#  Created by Tom Coleman on 2008-03-13.
#  Copyright 2008 Tom Coleman. All rights reserved.
#
#  This script reads the following in from Temp/:
#    algorithms -- a list of algorithms and their parameters
#    sigraphs   -- a list of problems
# 
#  It then saves to Results/ a directory either specified on the commandline
#  or generated by date, filled with the above plus
#    labellings
#    costs
#    timings
#    results

TD='Temp'
RD='Results'
AD='Algorithms'
ED='Execute'

TIME="/usr/bin/time -p"


. "$ED/algorithms.sh"; read_algorithms

echo -n > "$TD/timing"
echo -n > "$TD/labellings"

n_algs=${#algs[*]}
for (( i = 0; i < $n_algs; i++ )); do
	exestr="./$AD/${algs[${i}]}"
	
	echo "running $exestr"
	$TIME 2>> "$TD/timing" $exestr >> "$TD/labellings" < "$TD/sigraphs" || exit
#	$exestr >> "$TD/labellings" < "$TD/sigraphs" || exit
	if [[ $i > 0 ]]; then
		echo >> "$TD/labellings"
	fi
done

n_probs=$(cat "$TD/sigraphs" | wc -l)

# prepare the input for costs
cat "$TD/labellings" | csplit -n 4 -f "$TD/xx" -k -s - $(($n_probs + 1)) {$(($n_algs - 2))}
cat "$TD/sigraphs" | paste -d "\n" - "$TD"/xx* > "$TD/costs_input"
rm "$TD"/xx*

echo cat "$TD/costs_input" pipe "./$ED/costs.exe" $n_probs $n_algs into "$TD/costs" or exit
cat "$TD/costs_input" | "./$ED/costs.exe" $n_probs $n_algs > "$TD/costs" || exit
rm "$TD/costs_input"

cat "$TD/costs" | "./$ED/make_results.py" | tee "$TD/results"
times=$(cat "$TD/timing" | grep "user" | sed 's/user *//g' | paste -s -d ',' - | sed 's/,/, /g')
echo "times: $times" | tee -a "$TD/results"

